### ISSUE TITLE
Update of the GER region pages.

### ISSUE THREAD

**Issue by pbrenton** [AtlasOfLivingAustralia/regions#3]
*migrated from:* https://code.google.com/p/ala/issues/detail?id=633
*date:* Wed Apr  9 21:55:02 2014
*author:* CoolDa...@gmail.com
 ---

See below thread.
The most recent SHP file for the GER region and it's partner sub-regions was loaded into the spatial portal by Chris Flemming in about Oct/Nov last year - see image attached. I presume that the regions page just needs to be updated to link to the new polygons (including the additional sub-regions), instead of the old polys, but this may be a bit simplistic. If you need the original SHP file for a reload, I should have it.

Peter B.

From: Martin, Dave (CES, Black Mountain)
Sent: Thu 10/04/2014 2:32 PM

There isnt an admin screen for this.  For adding the new layer, just create an issue and I'll probably assign to Adam. Do you know where the layer is ? 

Dave
________________________________________
From: Brenton, Peter (CES, Black Mountain)
Sent: 09 April 2014 16:56
To: Martin, Dave (CES, Black Mountain)
Subject: FW: Amendment to GER pages on ALA site
Dave,
 
Am I able to change the content on the GER region page?
 
Also, Chris Flemming did add the new GER region boundary and also the amended and additional sub-regions to the spatial portal, but they never made their way into the regions page. Can this be updated easily?
 
Thanks
 
Peter B
 
From: Tandi Spencer-Smith [[mailto:tandiss@npansw.org.au](mailto:tandiss@npansw.org.au)] 
Sent: Tuesday, 8 April 2014 9:29 AM
To: Brenton, Peter (CES, Black Mountain)
Cc: Gary Howling
Subject: NB: Amendment to GER pages on ALA site
 
Hi Peter
 
Was on the ALA website earlier and noticed that the figure for the size of the corridor is incorrect. Would be most appreciative if you could please change it from 1,200 km to 3,600 km. 
[http://regions.ala.org.au/layer/Great%20Eastern%20Ranges](http://regions.ala.org.au/layer/Great%20Eastern%20Ranges)
 
Also the polygon used on this page: [http://regions.ala.org.au/#rt=other&region=Great+Eastern+Ranges](http://regions.ala.org.au/#rt=other&region=Great+Eastern+Ranges) is apparently out of date and a new one was supplied a little while back. Are you able to please organise for this to be updated? We are looking to link to this map from our GER Landcare Grants page so that landholders wanting to apply for grants can check if they are located within the corridor.
 
Kind regards,
Tandi

Tandi Spencer - Smith
Communications Manager
National Parks Association of NSW & Great Eastern Ranges Initiative (GER)
PO Box 337 | Newtown 2042 | New South Wales
T 02 9299 0000 | D 02 8580 6609
W [http://www.npansw.org.au](http://www.npansw.org.au) | E tandiss@npansw.org.au

**Comment by djtfmartin** [comment]
i believe this is done
