### ISSUE TITLE
Download button/action not respecting selected species group

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/regions#45]
Download button on a region page seems to download all records for a region but users expect download to reflect the records list and map - so should only include records in the selected "group" column.

As reported by robbibt@gmail.com:

> Hi ALA,

> I have been trying to download a set of records for certain organism classifications within the boundary of the Murray-Darling Basin using the portal here: http://regions.ala.org.au/Major%20drainage%20divisions/DARLING%2520RIVER#group=Crustaceans&subgroup=&from=1850&to=2015&tab=speciesTab

> Selecting a classification on the left successfully updates the map on the right with the relevant records, but when I come to downloading the subset of records using the "Download Records", I get a 28mb file containing only "bird" records regardless of what subset of records I have selected (i.e. selecting either amphibians or molluscs results in a dataset of birds being downloaded.

> I was wondering if you can replicate this on your end, or point me in the direction of a work-around?

> Cheers,

> Robbi Bishop-Taylor

**Comment by aruizca** [comment]
Fixed in release version 2.3
It is already in PROD
