### ISSUE TITLE
How can a subgroup have more records than a group?

### ISSUE THREAD

**Issue by aruizca** [AtlasOfLivingAustralia/regions#46]
Can any of you @nickdos or @djtfmartin help me to find out why the following is happening: 
In the bug report that I fixed today the user gave us the following url: http://regions.ala.org.au/Major%20drainage%20divisions/DARLING%2520RIVER#group=Crustaceans&subgroup=&from=1850&to=2015&tab=speciesTab with a total of 861 records. How come if you select the next subgroup "Fairy shrimp, Clam shrimp" we get 964 records -> http://regions.ala.org.au/Major%20drainage%20divisions/DARLING%2520RIVER#group=Crustaceans&subgroup=Fairy+shrimp,+Clam+shrimp&from=1850&to=2015&tab=speciesTab

* In the first instance the following URL generated and executed: http://biocache.ala.org.au/ws/occurrences/search?q=cl1059%3A%22DARLING+RIVER%22&facets=names_and_lsid&fsort=taxon_name&pageSize=0&flimit=50&foffset=0&fq=rank%3A%28species+OR+subspecies%29+AND+species_group%3A%22Crustaceans%22

* When subgroup is selected the following URL is generated: http://biocache.ala.org.au/ws/occurrences/search?q=cl1059%3A%22DARLING+RIVER%22&facets=names_and_lsid&fsort=taxon_name&pageSize=0&flimit=50&foffset=0&fq=rank%3A%28species+OR+subspecies%29+AND+species_subgroup%3A%22Fairy+shrimp%2C+Clam+shrimp%22

**Comment by djtfmartin** [comment]
Im guessing this is a bug with the subgroups config.

**Comment by nickdos** [comment]
This is a duplicate issue of https://github.com/AtlasOfLivingAustralia/biocache-service/issues/50

This has been happening for a while so is not related to the new `subgroups.json` that was deployed yesterday.

**Comment by nickdos** [comment]
Not sure this is a strict duplicate but definitely related... Re-opening issue so this is tested for, specifically.

**Comment by nickdos** [comment]
This issue was moved to AtlasOfLivingAustralia/biocache-service#51
