### ISSUE TITLE
regions/regionList should return an HTTP error code if no type, or an unrecognised type is given in parameters

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/regions#57]
The ``regions/regionList`` API is silently returning nothing currently if no type or an unrecognised type is given. It would be easier to diagnose if there was an error response code, and a JSON error message that indicated the ``type`` parameter was missing or unrecognised and is required to get non-trivial results.

https://github.com/AtlasOfLivingAustralia/regions/blob/8ac25b990a0dd301b1a86115d9939972d2885a6a/grails-app/controllers/au/org/ala/regions/RegionsController.groovy#L62

**Comment by adam-collins** [comment]
will resolve with #75
