### ISSUE TITLE
Hardcoded regions CAS configuration

### ISSUE THREAD

**Issue by vjrj** [AtlasOfLivingAustralia/regions#64]
Seems that the CAS configuration in regions is somehow hardcoded.

Although we have this configured:
```
casProperties=casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilter,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath
casServerName=https://auth.gbif.es
casServerLoginUrl=https://auth.gbif.es/cas/login
casServerUrlPrefix=https://auth.gbif.es/cas
security.cas.logoutUrl=https://auth.gbif.es/cas/logout
security.cas.loginUrl=https://auth.gbif.es/cas/login
security.cas.bypass=false
```
we get these kind of errors:

```
java.io.IOException: Server returned HTTP response code: 502 for URL: https://auth.ala.org.au/cas/p3/serviceValidate?ticket=ST-9-C--d4lXHOo6Et-HHyoKAKNpNGCMauth.gbif.es&service=https%3A%2F%2Fregiones.gbif.es%2FalaAdmin%2F%3Bjsessionid%3D0B913B6261D33F9C93A3E3688CDA7F7A&filterClass=org.jasig.cas.client.validation.Cas30ProxyReceivingTicketValidationFilter&disableCAS=false
```

**Comment by vjrj** [comment]
Comparing regions application.groovy with:
https://github.com/AtlasOfLivingAustralia/ala-hub/blob/master/grails-app/conf/application.groovy
seems that it only configures the cas filters.

**Comment by nickdos** [comment]
I think you're mixing the old 2.x CAS config naming scheme with the newer 3.x scheme.

E.g. either all the CAS variables should have the `security.cas.` prefix or none of them should.

So first try adding `security.cas.` to all the vars. E.g. `security.cas.casServerName`.

**Comment by vjrj** [comment]
Thanks @nickdos for your fast response. So for compatibility with the two versions of cas, I think we should duplicate the old and new cas vars, no?
https://github.com/AtlasOfLivingAustralia/ala-install/blob/master/ansible/roles/regions/templates/regions-config.properties

**Comment by vjrj** [comment]
Forget me, I'll try to patch ala-install with similar vars than other roles.

**Comment by nickdos** [comment]
That regions ansible properties file is also incorrect. The reason it was not picked up is due to CAS 3.x providing default values when no var is provided. The default vars are ALA specific, which is why you see ALA URLs in the error message. I'll get someone to fix that file.

**Comment by vjrj** [comment]
Don't worry. I have a fix tested. I'll send the PR ASAP. Thanks @nickdos
