### ISSUE TITLE
Links to biocache have un-encoded double-quote characters

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/regions#67]
Some links from regions to biocache have unencoded double quote characters. In most browsers this is not an issue, but we still have some IE11/Win7 government users and one of them reported this issue. Replicated in Citrix Workspace IE11

The issue is that the `%22` in the following (which Firefox generated for me) is a `"` without percent-encoding in IE11:

```
https://biocache.ala.org.au/occurrences/search?q=cl10912%3A%22Apollo+Marine+Park%22&fq=occurrence_year%3A%5B*+TO+2019-12-31T23%3A59%3A59Z%5D&fq=rank%3A%28species+OR+subspecies%29&fq=-occurrence_status_s%3Aabsent&fq=geospatial_kosher%3Atrue&fq=occurrence_year%3A*
```

IE11 seems to be using this version:

```
https://biocache.ala.org.au/occurrences/search?q=cl10912%3A"Apollo+Marine+Park"&fq=occurrence_year%3A%5B*+TO+2019-12-31T23%3A59%3A59Z%5D&fq=rank%3A%28species+OR+subspecies%29&fq=-occurrence_status_s%3Aabsent&fq=geospatial_kosher%3Atrue&fq=occurrence_year%3A*
```

The regions page for testing purposes and links for testing are both the "View Records" and any of "List records" buttons that appear when clicking on species names:

```
https://regions.ala.org.au/Marine%20parks/Apollo%2520Marine%2520Park#group=ALL_SPECIES&subgroup=&guid=&from=1850&to=2019&tab=speciesTab&fq=
```

Refs ticket 35977 in helpdesk

**Comment by M-Nicholls** [comment]
tested ok on IE 11.678
https://biocache-test.ala.org.au/occurrences/search?q=cl10912%3A%22Apollo+Marine+Park%22&fq=occurrence_year%3A%5B*+TO+2019-12-31T23%3A59%3A59Z%5D&fq=rank%3A%28species+OR+subspecies%29&fq=-occurrence_status_s%3Aabsent&fq=geospatial_kosher%3Atrue&fq=occurrence_year%3A*&fq=lsid%3A%22NZOR-6-26071%22
