### ISSUE TITLE
Reptiles section empty for some regions

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/regions#69]
Reported by a user: https://support.ehelp.edu.au/a/tickets/36546

https://regions.ala.org.au/feature/5388410?q=cl914:%22Simpson%20Desert%22?q=cl914:%22Simpson%20Desert%22?q=cl914:%22Simpson%20Desert%22?q=cl914%3A%22Simpson+Desert%22&fq=species_subgroup%3A%22Lizards%2C+Snakes%22&fq=occurrence_year%3A%5B*+TO+2019-12-31T23%3A59%3A59Z%5D&fq=rank%3A%28species+OR+subspecies%29&fq=-occurrence_status_s%3Aabsent&fq=geospatial_kosher%3Atrue&fq=occurrence_year%3A*#group=Reptiles&subgroup=Lizards,+Snakes&guid=&from=1850&to=2019&tab=speciesTab&fq=species_subgroup%3A%22Lizards,+Snakes%22

Reptiles section shows no records by the child category (Lizards and snakes) does have records.

**Comment by M-Nicholls** [comment]
tested ok

https://regions-test.ala.org.au/feature/5388410?q=cl914:%22Simpson%20Desert%22?q=cl914:%22Simpson%20Desert%22?q=cl914:%22Simpson%20Desert%22?q=cl914%3A%22Simpson+Desert%22&fq=species_subgroup%3A%22Lizards%2C+Snakes%22&fq=occurrence_year%3A[*+TO+2019-12-31T23%3A59%3A59Z]&fq=rank%3A(species+OR+subspecies)&fq=-occurrence_status_s%3Aabsent&fq=geospatial_kosher%3Atrue&fq=occurrence_year%3A*#group=Reptiles&subgroup=&guid=&from=1850&to=2019&tab=speciesTab&fq=species_subgroup%3A(%22Lizards,%20Snakes%22)
