### ISSUE TITLE
URL encoding issue for regions with special characters

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/regions#75]
The regions app uses place names parameters in URLs from the main map
<img width="1525" alt="Screen Shot 2020-03-23 at 5 50 28 pm" src="https://user-images.githubusercontent.com/444897/77346865-d2c0df00-6d2e-11ea-9b3d-c0d7cd0e8267.png">
links to
https://regions.ala.org.au/Biogeographic%20regions/Arnhem%2520Plateau

<img width="1530" alt="Screen Shot 2020-03-23 at 5 50 35 pm" src="https://user-images.githubusercontent.com/444897/77346880-d8b6c000-6d2e-11ea-956f-db12dfbabb81.png">

There issues with this approach for place names with special characters which causes the URLs to break. 
Suggest this functionality is changed to use the ID of the region instead of the place name to avoid these issues.

this issue has been reported by @shahmanash and the Austrian Atlas team.

**Comment by adam-collins** [comment]
Adding the region (or subregion) pid to the URL is supported and bypasses the name lookup.
