### ISSUE TITLE
Regions app download doesnt contain dataResourceUid

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/regions#9]
_From @djtfmartin on August 19, 2014 12:59_

*migrated from:* https://code.google.com/p/ala/issues/detail?id=601
*date:* Tue Mar  4 20:31:28 2014
*author:* moyesyside
 ---

Regions app download doesnt contain dataResourceUid

_Copied from original issue: AtlasOfLivingAustralia/biocache-hubs#61_

**Comment by nickdos** [comment]
Extra fields for downloads can be specified by adding them to the download URL via the appropriate param (see API docs). Moving to regions app.

**Comment by aruizca** [comment]
Fixed in #43
