### ISSUE TITLE
Add 'Download species count' option in regions

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/regions#97]
Could we add a "Download species count" function to Regions?

The new button would go next to "Download records", and the output would be similar to that seen on the app: a list of species in one column and the number of records for each in a second column.

![Image](https://user-images.githubusercontent.com/90439797/222346275-01cb1af5-5d3b-495d-b39c-eb6301cf6058.png)

(Reported by Shandiya, requested by several councils)

**Comment by sat01a** [comment]
Assigned to @adam-collins and will be fixed in the next release 
cc: @shandiya @kylie-m

**Comment by sughics** [comment]
Addressed here: https://github.com/AtlasOfLivingAustralia/ala-hub/releases/tag/5.0.2

**Comment by sughics** [comment]
Released with ala-hub 5.0.2
